---
# This action performs a lint of markdown files in the repository

# Name of the action
name: Markdown Linting

# Events which trigger the action
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  markdownlint:
    name: Lint markdown (.md) files
    runs-on: ubuntu-latest

    steps:
      # checkout action documentation
      # https://github.com/marketplace/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # markdownlint-cli action documentation
      # https://github.com/marketplace/actions/markdownlint-cli
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .markdownlint.json
